---
- name: Deploy YOLO Application
  hosts: all
  become: true

  vars:
    app_dir: /opt/yolo


  pre_tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Clone YOLO repo from my github repo
      git:
        repo: https://github.com/NicholasMariga/yolo.git
        dest: "{{ app_dir }}"
        force: yes

    - name: Install Docker
      package:
        name: docker
        state: present
    - name: Install Docker Compose
      package:
        name: docker-compose
        state: present

    - name: Install dependencies
      package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - python3-pip

    - name: Install Docker Python SDK
      pip:
        name: docker
        state: present


  roles:
    - role: app-mongodb
    - role: app-client
    - role: app-backend