version: "3.8"

services:

  app-client:
    build: ./client
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on: 
      - app-backend
    networks:
      - app-net

  app-backend:
    build: ./backend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5000:5000"
    depends_on: 
      - app-ip-mongo
    networks:
      - app-net

 
  app-ip-mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-net
    volumes:
      - type: volume
        source: app-mongo-data
        target: /data/db


networks:
  app-net:
    name: app-net
    driver: bridge
    attachable: true


volumes:
  app-mongo-data:
    driver: local