---
- name: Build frontend Docker image
  community.docker.docker_image:
    name: app-client
    source: build
    build:
      path: "{{ app_dir }}/client"
    state: present
  become: true

- name: Start frontend container
  community.docker.docker_container:
    name: app-client
    image: app-client
    state: started
    published_ports:
      - "3000:3000"
    networks:
      - name: app-net
    stdin_open: true
    tty: yes
    interactive: yes
    restart_policy: always
  become: true
